Revert "ci: enable benchmarking for windows"
This reverts commit 4356a8f0d0148835b87cd8463f2b8e9b82a078a5.

The reason for this revert is that publishing the
benchmark results failed with the following error:

```
mkdir: D:\a\_temp\7b514a37-675e-4b59-90db-e2c0e048869e.ps1:2
Line |
   2 |  mkdir --parents benchmarks/windows-2022/
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A positional parameter cannot be found that
accepts argument 'benchmarks/windows-2022/'.
Error: Process completed with exit code 1.
```